package followup

import (
	"time"

	"github.com/google/uuid"
)

type CreateFollowUpRequest struct {
	PatientID       uuid.UUID        `json:"patient_id"`
	DoctorID        *uuid.UUID       `json:"doctor_id,omitempty"`
	AppointmentID   *uuid.UUID       `json:"appointment_id,omitempty"`
	MedicalRecordID *uuid.UUID       `json:"medical_record_id,omitempty"`
	Reason          string           `json:"reason"`
	DueDate         time.Time        `json:"due_date"`
	Priority        FollowUpPriority `json:"priority"`
	AutoGenerated   bool             `json:"auto_generated"`
}

type UpdateFollowUpStatusRequest struct {
	Status FollowUpStatus `json:"status"`
}

type FollowUpResponse struct {
	Data    interface{} `json:"data"`
	Message string      `json:"message"`
	Error   string      `json:"error,omitempty"`
}
