package followup

import (
	"time"

	"github.com/google/uuid"
)

type FollowUpStatus string

const (
	StatusPending   FollowUpStatus = "pending"
	StatusCompleted FollowUpStatus = "completed"
	StatusMissed    FollowUpStatus = "missed"
	StatusCanceled  FollowUpStatus = "canceled"
)

type FollowUpPriority string

const (
	PriorityLow    FollowUpPriority = "low"
	PriorityMedium FollowUpPriority = "medium"
	PriorityHigh   FollowUpPriority = "high"
)

type FollowUp struct {
	ID              uuid.UUID        `json:"id"`
	TenantID        uuid.UUID        `json:"tenant_id"`
	PatientID       uuid.UUID        `json:"patient_id"`
	DoctorID        *uuid.UUID       `json:"doctor_id,omitempty"`
	AppointmentID   *uuid.UUID       `json:"appointment_id,omitempty"`
	MedicalRecordID *uuid.UUID       `json:"medical_record_id,omitempty"`
	Reason          string           `json:"reason"`
	DueDate         time.Time        `json:"due_date"`
	Status          FollowUpStatus   `json:"status"`
	Priority        FollowUpPriority `json:"priority"`
	AutoGenerated   bool             `json:"auto_generated"`
	CreatedBy       uuid.UUID        `json:"created_by"`
	CompletedAt     *time.Time       `json:"completed_at,omitempty"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`

	// Enriched fields for DTOs
	PatientName string `json:"patient_name,omitempty"`
	DoctorName  string `json:"doctor_name,omitempty"`
}
