package followup

import (
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

type Repository interface {
	Create(f *FollowUp) error
	GetByID(tenantID, id uuid.UUID) (*FollowUp, error)
	GetByPatient(tenantID, patientID uuid.UUID) ([]FollowUp, error)
	Update(f *FollowUp) error
	List(tenantID uuid.UUID, filters ListFilters) ([]FollowUp, error)
	GetUpcomingReminders(beforeTime time.Time) ([]FollowUp, error)
	MarkOverdueAsMissed(beforeTime time.Time) (int64, error)
}

type ListFilters struct {
	Status   string
	DoctorID *uuid.UUID
	Overdue  bool
	DueToday bool
}

type postgresRepository struct {
	db *sql.DB
}

func NewPostgresRepository(db *sql.DB) Repository {
	return &postgresRepository{db: db}
}

func (r *postgresRepository) Create(f *FollowUp) error {
	query := `
		INSERT INTO follow_ups (
			id, tenant_id, patient_id, doctor_id, appointment_id, medical_record_id,
			reason, due_date, status, priority, auto_generated, created_by, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
	`
	_, err := r.db.Exec(
		query,
		f.ID, f.TenantID, f.PatientID, f.DoctorID, f.AppointmentID, f.MedicalRecordID,
		f.Reason, f.DueDate, f.Status, f.Priority, f.AutoGenerated, f.CreatedBy, f.CreatedAt, f.UpdatedAt,
	)
	return err
}

func (r *postgresRepository) GetByID(tenantID, id uuid.UUID) (*FollowUp, error) {
	query := `
		SELECT 
			f.id, f.tenant_id, f.patient_id, f.doctor_id, f.appointment_id, f.medical_record_id,
			f.reason, f.due_date, f.status, f.priority, f.auto_generated, f.created_by,
			f.completed_at, f.created_at, f.updated_at,
			p.first_name || ' ' || p.last_name as patient_name,
			COALESCE(d.full_name, '') as doctor_name
		FROM follow_ups f
		JOIN patients p ON p.id = f.patient_id AND p.tenant_id = f.tenant_id
		LEFT JOIN doctors d ON d.id = f.doctor_id AND d.tenant_id = f.tenant_id
		WHERE f.id = $1 AND f.tenant_id = $2
	`
	f := &FollowUp{}
	err := r.db.QueryRow(query, id, tenantID).Scan(
		&f.ID, &f.TenantID, &f.PatientID, &f.DoctorID, &f.AppointmentID, &f.MedicalRecordID,
		&f.Reason, &f.DueDate, &f.Status, &f.Priority, &f.AutoGenerated, &f.CreatedBy,
		&f.CompletedAt, &f.CreatedAt, &f.UpdatedAt, &f.PatientName, &f.DoctorName,
	)
	if err == sql.ErrNoRows {
		return nil, ErrNotFound
	}
	return f, err
}

func (r *postgresRepository) GetByPatient(tenantID, patientID uuid.UUID) ([]FollowUp, error) {
	query := `
		SELECT 
			f.id, f.tenant_id, f.patient_id, f.doctor_id, f.appointment_id, f.medical_record_id,
			f.reason, f.due_date, f.status, f.priority, f.auto_generated, f.created_by,
			f.completed_at, f.created_at, f.updated_at,
			p.first_name || ' ' || p.last_name as patient_name,
			COALESCE(d.full_name, '') as doctor_name
		FROM follow_ups f
		JOIN patients p ON p.id = f.patient_id AND p.tenant_id = f.tenant_id
		LEFT JOIN doctors d ON d.id = f.doctor_id AND d.tenant_id = f.tenant_id
		WHERE f.patient_id = $1 AND f.tenant_id = $2
		ORDER BY f.due_date ASC
	`
	rows, err := r.db.Query(query, patientID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []FollowUp
	for rows.Next() {
		var f FollowUp
		err := rows.Scan(
			&f.ID, &f.TenantID, &f.PatientID, &f.DoctorID, &f.AppointmentID, &f.MedicalRecordID,
			&f.Reason, &f.DueDate, &f.Status, &f.Priority, &f.AutoGenerated, &f.CreatedBy,
			&f.CompletedAt, &f.CreatedAt, &f.UpdatedAt, &f.PatientName, &f.DoctorName,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, f)
	}
	return results, nil
}

func (r *postgresRepository) Update(f *FollowUp) error {
	query := `
		UPDATE follow_ups SET
			status = $1, completed_at = $2, updated_at = $3
		WHERE id = $4 AND tenant_id = $5
	`
	_, err := r.db.Exec(query, f.Status, f.CompletedAt, f.UpdatedAt, f.ID, f.TenantID)
	return err
}

func (r *postgresRepository) List(tenantID uuid.UUID, filters ListFilters) ([]FollowUp, error) {
	var whereClauses []string
	var args []interface{}
	n := 1

	whereClauses = append(whereClauses, fmt.Sprintf("f.tenant_id = $%d", n))
	args = append(args, tenantID)
	n++

	if filters.Status != "" {
		whereClauses = append(whereClauses, fmt.Sprintf("f.status = $%d", n))
		args = append(args, filters.Status)
		n++
	}

	if filters.DoctorID != nil {
		whereClauses = append(whereClauses, fmt.Sprintf("f.doctor_id = $%d", n))
		args = append(args, *filters.DoctorID)
		n++
	}

	if filters.Overdue {
		whereClauses = append(whereClauses, "f.due_date < NOW() AND f.status = 'pending'")
	} else if filters.DueToday {
		whereClauses = append(whereClauses, "f.due_date::date = CURRENT_DATE")
	}

	query := `
		SELECT 
			f.id, f.tenant_id, f.patient_id, f.doctor_id, f.appointment_id, f.medical_record_id,
			f.reason, f.due_date, f.status, f.priority, f.auto_generated, f.created_by,
			f.completed_at, f.created_at, f.updated_at,
			p.first_name || ' ' || p.last_name as patient_name,
			COALESCE(d.full_name, '') as doctor_name
		FROM follow_ups f
		JOIN patients p ON p.id = f.patient_id AND p.tenant_id = f.tenant_id
		LEFT JOIN doctors d ON d.id = f.doctor_id AND d.tenant_id = f.tenant_id
		WHERE ` + strings.Join(whereClauses, " AND ") + `
		ORDER BY f.due_date ASC
	`
	rows, err := r.db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []FollowUp
	for rows.Next() {
		var f FollowUp
		err := rows.Scan(
			&f.ID, &f.TenantID, &f.PatientID, &f.DoctorID, &f.AppointmentID, &f.MedicalRecordID,
			&f.Reason, &f.DueDate, &f.Status, &f.Priority, &f.AutoGenerated, &f.CreatedBy,
			&f.CompletedAt, &f.CreatedAt, &f.UpdatedAt, &f.PatientName, &f.DoctorName,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, f)
	}
	return results, nil
}

func (r *postgresRepository) GetUpcomingReminders(beforeTime time.Time) ([]FollowUp, error) {
	query := `
		SELECT 
			f.id, f.tenant_id, f.patient_id, f.doctor_id, f.appointment_id, f.medical_record_id,
			f.reason, f.due_date, f.status, f.priority, f.auto_generated, f.created_by,
			f.completed_at, f.created_at, f.updated_at,
			p.first_name || ' ' || p.last_name as patient_name,
			COALESCE(d.full_name, '') as doctor_name
		FROM follow_ups f
		JOIN patients p ON p.id = f.patient_id AND p.tenant_id = f.tenant_id
		LEFT JOIN doctors d ON d.id = f.doctor_id AND d.tenant_id = f.tenant_id
		WHERE f.status = 'pending' AND f.due_date <= $1 AND f.due_date > NOW()
	`
	rows, err := r.db.Query(query, beforeTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []FollowUp
	for rows.Next() {
		var f FollowUp
		err := rows.Scan(
			&f.ID, &f.TenantID, &f.PatientID, &f.DoctorID, &f.AppointmentID, &f.MedicalRecordID,
			&f.Reason, &f.DueDate, &f.Status, &f.Priority, &f.AutoGenerated, &f.CreatedBy,
			&f.CompletedAt, &f.CreatedAt, &f.UpdatedAt, &f.PatientName, &f.DoctorName,
		)
		if err != nil {
			return nil, err
		}
		results = append(results, f)
	}
	return results, nil
}

func (r *postgresRepository) MarkOverdueAsMissed(beforeTime time.Time) (int64, error) {
	query := `
		UPDATE follow_ups SET status = 'missed', updated_at = NOW()
		WHERE status = 'pending' AND due_date < $1
	`
	res, err := r.db.Exec(query, beforeTime)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
