package followup

import (
	"context"
	"time"

	"clinic-backend/internal/notification"
	"github.com/google/uuid"
)

type Service struct {
	repo       Repository
	dispatcher *notification.NotificationDispatcher
}

func NewService(repo Repository, dispatcher *notification.NotificationDispatcher) *Service {
	return &Service{
		repo:       repo,
		dispatcher: dispatcher,
	}
}

func (s *Service) CreateFollowUp(tenantID, userID uuid.UUID, req CreateFollowUpRequest) (*FollowUp, error) {
	if req.DueDate.Before(time.Now()) {
		return nil, ErrInvalidDueDate
	}

	f := &FollowUp{
		ID:              uuid.New(),
		TenantID:        tenantID,
		PatientID:       req.PatientID,
		DoctorID:        req.DoctorID,
		AppointmentID:   req.AppointmentID,
		MedicalRecordID: req.MedicalRecordID,
		Reason:          req.Reason,
		DueDate:         req.DueDate,
		Status:          StatusPending,
		Priority:        req.Priority,
		AutoGenerated:   req.AutoGenerated,
		CreatedBy:       userID,
		CreatedAt:       time.Now(),
		UpdatedAt:       time.Now(),
	}

	if err := s.repo.Create(f); err != nil {
		return nil, err
	}

	// Trigger immediate notification if priority is high or requested
	// This will be handled by the dispatcher using preferences
	if s.dispatcher != nil {
		_ = s.dispatcher.Dispatch(context.Background(), notification.AppointmentEventPayload{
			TenantID:      tenantID,
			PatientID:     req.PatientID,
			AppointmentID: f.ID, // Using follow-up ID as context
			ActorID:       userID,
			Event:         "FOLLOW_UP_CREATED",
			StartTime:     req.DueDate,
		})
	}

	return f, nil
}

func (s *Service) GetPatientFollowUps(tenantID, patientID uuid.UUID) ([]FollowUp, error) {
	return s.repo.GetByPatient(tenantID, patientID)
}

func (s *Service) UpdateStatus(tenantID, id uuid.UUID, status FollowUpStatus) error {
	f, err := s.repo.GetByID(tenantID, id)
	if err != nil {
		return err
	}

	if status == StatusCompleted {
		now := time.Now()
		f.CompletedAt = &now
	}

	f.Status = status
	f.UpdatedAt = time.Now()

	return s.repo.Update(f)
}

func (s *Service) ListFollowUps(tenantID uuid.UUID, filters ListFilters) ([]FollowUp, error) {
	return s.repo.List(tenantID, filters)
}

func (s *Service) ProcessReminders() error {
	// Remind for follow-ups due in next 24 hours
	tomorrow := time.Now().Add(24 * time.Hour)
	upcoming, err := s.repo.GetUpcomingReminders(tomorrow)
	if err != nil {
		return err
	}

	for _, f := range upcoming {
		if s.dispatcher != nil {
			_ = s.dispatcher.Dispatch(context.Background(), notification.AppointmentEventPayload{
				TenantID:      f.TenantID,
				PatientID:     f.PatientID,
				AppointmentID: f.ID,
				Event:         "FOLLOW_UP_REMINDER",
				StartTime:     f.DueDate,
			})
		}
	}

	return nil
}

func (s *Service) ProcessOverdue() (int64, error) {
	return s.repo.MarkOverdueAsMissed(time.Now())
}
